### ISSUE TITLE
Minor changes to semantics

### ISSUE THREAD

**Issue by ehildenb** [wolflo/k-brainfuck-semantics#1]
-    The `structural` attribute on rules doesn't mean anything anymore (not for LLVM/Haskell backends), so should be removed. It does affect Java backend, but only barely.
-   These rules can be `macro` so that they are expanded at parse-time, so they don't take execution steps when running (for speed): https://github.com/wolflo/k-brainfuck-semantics/blob/master/brainfuck.k#L26

**Comment by wolflo** [comment]
@ehildenb much appreciated! Fixed in #2.
